name: RPGMoney
main: beer.devs.rpgmoney.Main
author: LoneDev
version: 1.3.1
api-version: 1.20.5
depend:
  - Vault
softdepend:
  - ItemsAdder
libraries:
  - beer.devs:FastNbt-jar:1.4.15
  - net.kyori:adventure-api:4.18.0
  - net.kyori:adventure-text-serializer-gson:4.18.0
  - net.kyori:adventure-text-serializer-gson-legacy-impl:4.18.0
  - net.kyori:adventure-platform-bukkit:4.3.4
  - net.kyori:adventure-text-minimessage:4.18.0
commands:
  rpgmoney:
    description: "Main plugin command"
    usage: /rm
    aliases: [ rm, rmoney ]
permissions:
  rpgmoney.pickup:
    description: "Permission to pickup money"
    default: op
  rpgmoney.reload:
    description: "Permission to reload the plugin"
    default: op
  rpgmoney.get:
    description: "Permission to get your money as physical currency"
    default: op
